# Generated by Django 2.0.4 on 2018-04-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
