# Generated by Django 2.0.4 on 2018-04-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=2)),
                ('nacimiento', models.DateField()),
                ('ocupacion', models.CharField(max_length=255)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('observacion', models.TextField(max_length=5000)),
                ('ultima_atencion', models.DateTimeField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='F', max_length=2)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo electrónico')),
                ('peso', models.IntegerField(default=0)),
                ('glicemia_mgdl', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('nutri', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
