# Generated by Django 2.0.4 on 2018-04-30 14:15

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_auto_20180430_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='nacimiento',
            field=models.DateField(default=datetime.date.today, verbose_name='Nacimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ultima_atencion',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Ulima atencion'),
        ),
    ]
