# Generated by Django 2.0.4 on 2018-04-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20180430_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='glicemia_mgdl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ultima_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
