# Generated by Django 2.0.4 on 2018-05-01 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_auto_20180430_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='glicemia_mgdl',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ultima_atencion',
        ),
    ]
