# Generated by Django 2.0.4 on 2018-04-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0002_remove_alimento_porcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='kcal',
            field=models.FloatField(default=140),
        ),
    ]
