# Generated by Django 2.0.4 on 2018-04-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0003_auto_20180429_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculadora',
            name='porcion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
